"""added boolean

Revision ID: 757e555b067f
Revises: bd35860f7ffa
Create Date: 2020-08-17 21:07:10.540561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757e555b067f'
down_revision = 'bd35860f7ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('is_in_slider', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogpost', 'is_in_slider')
    # ### end Alembic commands ###
