"""empty message

Revision ID: 7abf0a24b153
Revises: 
Create Date: 2020-08-10 15:45:41.949383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abf0a24b153'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('second_name', sa.String(length=40), nullable=True),
    sa.Column('middle_name', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('avatar_file_path', sa.String(length=300), nullable=True),
    sa.Column('phonenumber', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_birthdate'), 'user', ['birthdate'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_middle_name'), 'user', ['middle_name'], unique=False)
    op.create_index(op.f('ix_user_second_name'), 'user', ['second_name'], unique=False)
    op.create_index(op.f('ix_user_sex'), 'user', ['sex'], unique=False)
    op.create_table('allergen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=True),
    sa.Column('allergen', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_patient'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnoz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=True),
    sa.Column('diagnoz', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_patient'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=True),
    sa.Column('id_vrach', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('zacklucheniye', sa.String(length=1000), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_patient'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_vrach'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_datetime'), 'event', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_datetime'), table_name='event')
    op.drop_table('event')
    op.drop_table('diagnoz')
    op.drop_table('allergen')
    op.drop_index(op.f('ix_user_sex'), table_name='user')
    op.drop_index(op.f('ix_user_second_name'), table_name='user')
    op.drop_index(op.f('ix_user_middle_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_birthdate'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
