"""added datetime

Revision ID: b3552188371a
Revises: 757e555b067f
Create Date: 2020-08-17 21:09:21.061613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3552188371a'
down_revision = '757e555b067f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogpost', 'datetime')
    # ### end Alembic commands ###
